Repository dumpus-app/dumpus-app, pull requests merged in 2023-07, with the labels that each got.

#217 feat: add translation guide (close #212)
  TRANSLATING.md
  src/app/[locale]/layout.tsx
Labels: documentation, enhancement

#214 fix: remove images from locales (close #196)
  locales/en.json
  public/assets/onboarding/en/android/privacy.png
  public/assets/onboarding/en/android/request.png
  public/assets/onboarding/en/android/settings.png
  public/assets/onboarding/en/desktop/privacy.png
  public/assets/onboarding/en/desktop/request.png
  public/assets/onboarding/en/desktop/settings.png
  public/assets/onboarding/en/ios/privacy.png
  public/assets/onboarding/en/ios/request.png
  public/assets/onboarding/en/ios/settings.png
  public/assets/onboarding/fr/android/step1.jpg
  public/assets/onboarding/fr/android/step2.jpg
  public/assets/onboarding/fr/android/step3.jpg
  public/assets/onboarding/fr/desktop/step1.png
  public/assets/onboarding/fr/desktop/step2.png
  public/assets/onboarding/fr/desktop/step3.png
  src/app/[locale]/onboarding/setup/_components/StepImage.tsx
  src/app/[locale]/onboarding/setup/_hooks/use-translation-data.ts
  src/app/[locale]/onboarding/setup/page.tsx
Labels: bug

#228 Refactor package loading (close #223)
  src/app/[locale]/onboarding/loading/_components/Error.tsx
  src/app/[locale]/onboarding/loading/_components/ProcessLoading.tsx
  src/app/[locale]/onboarding/loading/_components/Progress.tsx
  src/app/[locale]/onboarding/loading/_components/Retry.tsx
  src/app/[locale]/onboarding/loading/_hooks/use-logic.ts
  src/app/[locale]/onboarding/loading/page.tsx
Labels: bug, enhancement

#226 Credits page (close #194)
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/assets/contributors/aim.exe.png
  public/assets/contributors/androz2091.png
  public/assets/contributors/florian_lefebvre.png
  public/assets/contributors/gamers_indo1223.png
  public/assets/contributors/hunam.png
  public/assets/contributors/jazzyarmando1234.png
  public/assets/contributors/kaki87.png
  public/assets/contributors/lukebtw.png
  public/assets/contributors/mampo.png
  public/assets/contributors/mariusbegby.png
  public/assets/contributors/monwg.png
  public/assets/contributors/thearchaeopteryx.png
  src/app/[locale]/(app)/credits/_components/Back.tsx
  src/app/[locale]/(app)/credits/_components/Contributors.tsx
  src/app/[locale]/(app)/credits/_components/Flag.tsx
  src/app/[locale]/(app)/credits/_components/PageHeader.tsx
  src/app/[locale]/(app)/credits/_components/Roles.tsx
  src/app/[locale]/(app)/credits/page.tsx
  src/app/[locale]/(app)/settings/_components/About.tsx
  src/components/data/DetailCard.tsx
  src/data/contributors.json
  src/utils/index.ts
Labels: enhancement

#239 fix(SharePopup): use png encoding for avatars
  src/app/[locale]/(app)/_components/SharePopup.tsx
Labels: bug

#285 feat: allow resume package loading (close #278)
  locales/en.json
  src/app/[locale]/_components/LoadingScreen.tsx
  src/app/[locale]/onboarding/loading/_hooks/use-logic.ts
  src/app/[locale]/onboarding/loading/page.tsx
  src/stores/config.ts
Labels: enhancement

#286 fix: prevent toast at startup (close #283)
  src/components/InAppPurchasesDialog.tsx
Labels: bug

#292 close #283
  src/app/[locale]/(app)/settings/_components/Actions.tsx
  src/app/[locale]/_components/LoadingScreen.tsx
  src/app/_hooks/use-scroll-top.ts
  src/app/layout.tsx
  src/capacitor/hooks.ts
  src/capacitor/index.ts
  src/capacitor/purchases.ts
  src/components/InAppPurchasesDialog.tsx
  src/hooks/use-layout.ts
  src/stores/index.ts
  src/stores/purchases.ts
  src/utils/emitter.ts
Labels: bug, enhancement

#293 feat: translate time ranges (close #289)
  locales/en.json
  src/app/[locale]/(app)/(nav)/_components/BottomNav.tsx
  src/app/[locale]/(app)/(nav)/_components/TimeSelector.tsx
  src/hooks/use-sql-init.ts
  src/stores/config.ts
  src/stores/database.ts
  src/stores/index.ts
  src/stores/migrations.ts
Labels: bug, enhancement

#290 Add new translations (close #282)
  locales/en.json
  pnpm-lock.yaml
  src/app/[locale]/(app)/_components/SharePopup.tsx
  src/app/[locale]/(app)/settings/_components/Actions.tsx
  src/app/[locale]/onboarding/_components/Footer.tsx
  src/app/[locale]/onboarding/loading/_components/QueueDisplay.tsx
  src/app/_components/Error.tsx
  src/capacitor/hooks.ts
  src/components/InAppPurchasesDialog.tsx
  src/components/NoDataAvailable.tsx
  src/components/NotFoundState.tsx
  src/components/PremiumBadge.tsx
  src/components/Section.tsx
  src/components/StaticShareImage.tsx
  src/components/data/AvatarCard.tsx
Labels: enhancement
